src/Crija/Bundle/ReminderBundle/Entity/Event.php
<?php

namespace Crija\Bundle\ReminderBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Event
 *
 * @ORM\Table(name="event")
 * @ORM\Entity(repositoryClass="Crija\Bundle\ReminderBundle\Entity\EventRepository")
 */
class Event {

  /**
   * @var integer
   *
   * @ORM\Column(name="id", type="integer")
   * @ORM\Id
   * @ORM\GeneratedValue(strategy="AUTO")
   */
  private $id;

 /**
  * @Orm\ManyToOne(targetEntity="Jalis\Bundle\UserBundle\Entity\User", inversedBy="events")
  */
  private $user;

  /**
   * @var string
   *
   * @ORM\Column(name="type", type="string", length=255)
   */
  private $type;

  /**
   * @var boolean
   *
   * @ORM\Column(name="active", type="boolean")
   */
  private $active;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="startedAt", type="datetime")
   */
  private $startedAt;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="createdAt", type="datetime", nullable=true)
   */
  private $createdAt;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="updatedAt", type="datetime", nullable=true)
   */
  private $updatedAt;

  /**
   * @var \DateTime
   *
   * @ORM\Column(name="completedAt", type="datetime", nullable=true)
   */
  private $completedAt;

  /**
   * @var string
   *
   * @ORM\Column(name="message", type="text", nullable=true)
   */
  private $message;

  /**
   * @var string
   *
   * @ORM\Column(name="periodicity", type="text", nullable=true)
   */
  private $periodicity;

  /**
   * Get id
   *
   * @return integer 
   */
  public function getId() {
    return $this->id;
  }

  /**
   * Set startedAt
   *
   * @param \DateTime $startedAt
   * @return Event
   */
  public function setStartedAt($startedAt) {
    $this->startedAt = $startedAt;

    return $this;
  }

  /**
   * Get startedAt
   *
   * @return \DateTime 
   */
  public function getStartedAt() {
    return $this->startedAt;
  }

  /**
   * Set user
   *
   * @param string $user
   * @return Event
   */
  public function setUser(\Jalis\Bundle\UserBundle\Entity\User $user = null) {
    $this->user = $user;

    return $this;
  }

  /**
   * Get user
   *
   * @return string 
   */
  public function getUser() {
    return $this->user;
  }

  /**
   * Set type
   *
   * @param string $type
   * @return Event
   */
  public function setType($type) {
    $this->type = $type;

    return $this;
  }

  /**
   * Get type
   *
   * @return string 
   */
  public function getType() {
    return $this->type;
  }

  /**
   * Set active
   *
   * @param boolean $active
   * @return Event
   */
  public function setActive($active) {
    $this->active = $active;

    return $this;
  }

  /**
   * Get active
   *
   * @return boolean 
   */
  public function getActive() {
    return $this->active;
  }

  /**
   * Set createdAt
   *
   * @param \DateTime $createdAt
   * @return Event
   */
  public function setCreatedAt($createdAt) {
    $this->createdAt = $createdAt;

    return $this;
  }

  /**
   * Get createdAt
   *
   * @return \DateTime 
   */
  public function getCreatedAt() {
    return $this->createdAt;
  }

  /**
   * Set updatedAt
   *
   * @param \DateTime $updatedAt
   * @return Event
   */
  public function setUpdatedAt($updatedAt) {
    $this->updatedAt = $updatedAt;

    return $this;
  }

  /**
   * Get updatedAt
   *
   * @return \DateTime 
   */
  public function getUpdatedAt() {
    return $this->updatedAt;
  }

  /**
   * Set completedAt
   *
   * @param \DateTime $completedAt
   * @return Event
   */
  public function setCompletedAt($completedAt) {
    $this->completedAt = $completedAt;

    return $this;
  }

  /**
   * Get completedAt
   *
   * @return \DateTime 
   */
  public function getCompletedAt() {
    return $this->completedAt;
  }

  /**
   * Set message
   *
   * @param string $message
   * @return Event
   */
  public function setMessage($message) {
    $this->message = $message;

    return $this;
  }

  /**
   * Get message
   *
   * @return string 
   */
  public function getMessage() {
    return $this->message;
  }
  
  public function getPeriodicity() {
    return $this->periodicity;
  }

  public function setPeriodicity($periodicity) {
    $this->periodicity = $periodicity;
  }

    
  /**
   *
   * @ORM\PrePersist
   * @ORM\PreUpdate
   */
  public function updatedTimestamps() {
    $this->setUpdatedAt(new \DateTime('now'));

    if ($this->getCreatedAt() == null) {
      $this->setCreatedAt(new \DateTime('now'));
    }
  }
  /**
   * Get CountDown
   *
   * @return string 
   */
  public function getCountDown() {
   
    $today    = new \DateTime('now');
     
    $deadline = new \DateTime($this->completedAt->format('Y-m-d'));


   // $diff     = strtotime($deadline->modify($this->periodicity)->format('Y-m-d')) - strtotime($today->format('Y-m-d'));
      $diff     = strtotime($deadline->format('Y-m-d')) - strtotime($today->format('Y-m-d'));
    return $diff/86400;
    
  }
  /**
   * Get Priority
   *
   * @return string 
   */
  public function getPriority() {
    
    $today    = new \DateTime('now');
    $deadline = new \DateTime($this->completedAt->format('Y-m-d'));
    
 
    $diff     =  strtotime($deadline->modify($this->periodicity)->format('Y-m-d')) - strtotime($today->format('Y-m-d'));
	    
    $daysLeft = $diff/86400;
 
    
    $periodicidad =  (strtotime($this->periodicity) - time())/86400;
 
    $priority = round((($daysLeft*100)/$periodicidad)/4);
      /*
       * $phase =$daysLeft/4;

        if($phase = $priority*1)  {$priority_string = 'danger'; }
        if($phase < $priority*1 &&  $phase <= $priority*2)  {$priority_string = 'warning'; }
        if($phase < $priority*2 &&  $phase <= $priority*3)  {$priority_string = 'info'; }
        if($phase < $priority*4)  {$priority_string = 'success'; }
        */
    
 
    if($priority*1 >= 100) {$priority_string = 'success'; }
    if($priority*1 < 100 && $priority*2 > 50) {$priority_string = 'info'; }
    if($priority*2 <= 50 && $priority*4 > 25) {$priority_string = 'warning'; }
    if($priority*4 <= 25)  {$priority_string = 'danger'; }

    return $priority_string;
  }
  /**
   * Get EndDate
   *
   * @return string 
   */
  public function getEndDate() {
   
    
     
    $deadline = new \DateTime($this->completedAt->format('Y-m-d'));

    $endDate    = $deadline->modify($this->periodicity)->format('Y-m-d');
    
    return $endDate ;
    
  }
    /**
     * Get EndDate
     *
     * @return string
     */
    public function getPeriodo() {

        $periodo = $this->getPeriodicity();
        $periodo = str_replace("+", "", $periodo);
        $periodo = trim(str_replace("days", "", $periodo));

        return $periodo;

    }

}

src/Crija/Bundle/ReminderBundle/Controller/EventController.php
<?php

namespace Crija\Bundle\ReminderBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Crija\Bundle\ReminderBundle\Entity\Event;
use Crija\Bundle\ReminderBundle\Form\EventType;

/**
 * Event controller.
 *
 * @Route("/event")
 */
class EventController extends Controller
{

    /**
     * Lists all Event entities.
     *
     * @Route("/", name="event")
     * @Method("GET")
     * @Template()
     */
    public function indexAction()
    {
        $user = $this->get('security.context')->getToken()->getUser();
        
         if (!$user) {
            throw $this->createNotFoundException('Imposible localizar al usuario');
        }
      
        $em = $this->getDoctrine()->getManager();

        $entities = $em->getRepository('CrijaReminderBundle:Event')->findby(array('user' => $user));

      
        return array(
            'entities' => $entities,
        );
    }
    /**
     * Creates a new Event entity.
     *
     * @Route("/", name="event_create")
     * @Method("POST")
     * @Template("CrijaReminderBundle:Event:new.html.twig")
     */
    public function createAction(Request $request)
    {
      
        $user = $this->get('security.context')->getToken()->getUser();
        
         if (!$user) {
            throw $this->createNotFoundException('Imposible localizar al usuario');
        }
        $today = new \DateTime('now');
        $entity = new Event();
        $form = $this->createCreateForm($entity);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity->setActive('1');
            $entity->setUser($user);
            $entity->setCompletedAt($entity->getStartedAt());
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('event'));
        }

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Creates a form to create a Event entity.
     *
     * @param Event $entity The entity
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Event $entity)
    {
      
        $form = $this->createForm(new EventType(), $entity, array(
            'action' => $this->generateUrl('event_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * Displays a form to create a new Event entity.
     *
     * @Route("/new", name="event_new")
     * @Method("GET")
     * @Template()
     */
    public function newAction()
    {
        $entity = new Event();
        $form   = $this->createCreateForm($entity);

        return array(
            'entity' => $entity,
            'form'   => $form->createView(),
        );
    }

    /**
     * Finds and displays a Event entity.
     *
     * @Route("/{id}", name="event_show")
     * @Method("GET")
     * @Template()
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('CrijaReminderBundle:Event')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Event entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
     * Displays a form to edit an existing Event entity.
     *
     * @Route("/{id}/edit", name="event_edit")
     * @Method("GET")
     * @Template()
     */
    public function editAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('CrijaReminderBundle:Event')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Event entity.');
        }

        $editForm = $this->createEditForm($entity);
        $deleteForm = $this->createDeleteForm($id);

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }

    /**
    * Creates a form to edit a Event entity.
    *
    * @param Event $entity The entity
    *
    * @return \Symfony\Component\Form\Form The form
    */
    private function createEditForm(Event $entity)
    {
        $form = $this->createForm(new EventType(), $entity, array(
            'action' => $this->generateUrl('event_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }
    /**
     * Edits an existing Event entity.
     *
     * @Route("/{id}", name="event_update")
     * @Method("PUT")
     * @Template("CrijaReminderBundle:Event:edit.html.twig")
     */
    public function updateAction(Request $request, $id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('CrijaReminderBundle:Event')->find($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Event entity.');
        }

        $deleteForm = $this->createDeleteForm($id);
        $editForm = $this->createEditForm($entity);
        $editForm->handleRequest($request);

        if ($editForm->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('event', array('id' => $id)));
        }

        return array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        );
    }
    /**
     * Deletes a Event entity.
     *
     * @Route("/{id}", name="event_delete")
     * @Method("DELETE")
     */
    public function deleteAction(Request $request, $id)
    {
        $form = $this->createDeleteForm($id);
        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $entity = $em->getRepository('CrijaReminderBundle:Event')->find($id);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Event entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('event'));
    }

    /**
     * Creates a form to delete a Event entity by id.
     *
     * @param mixed $id The entity id
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm($id)
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('event_delete', array('id' => $id)))
            ->setMethod('DELETE')
            ->add('submit', 'submit', array('label' => 'Delete'))
            ->getForm()
        ;
    }
    /**
     * Events widget entity.
     *
     * @Route("/events-widget", name="widget")
     * @Template()
     */
    public function widgetAction(Request $request)
    {
     $user = $this->get('security.context')->getToken()->getUser();
        
        if (!$user) {
            throw $this->createNotFoundException('Imposible localizar al usuario');
        }
      
       $em     = $this->getDoctrine()->getManager();
       $entities = $em->getRepository('CrijaReminderBundle:Event')->findby(array('user' => $user));
        
       return array('entities' => $entities);
    }
   /**
     * Events widget entity.
     *
     * @Route("/events-number-widget", name="number")
     * @Template()
     */
    public function numberAction(Request $request)
    {
     $user = $this->get('security.context')->getToken()->getUser();
        
        if (!$user) {
            throw $this->createNotFoundException('Imposible localizar al usuario');
        }
      
       $em     = $this->getDoctrine()->getManager();
       $entities = $em->getRepository('CrijaReminderBundle:Event')->findby(array('user' => $user));
        
       return array('number' => count($entities));
    }
    
    /**
     * Change completed Event.
     *
     * @Route("/complete-reminder", name="complete-reminder")
     * @Template()
     */
    public function completeReminderAction(Request $request)
    {
       $user            = $this->get('security.context')->getToken()->getUser();
       $eventId         = $request->request->get('event');
       $completedAtGet  = $request->request->get('completedAt');
       $completedAtDate = new \Datetime($completedAtGet);
       
       
        if (!$user) {
            throw $this->createNotFoundException('Imposible localizar al usuario');
        }
      
       $em     = $this->getDoctrine()->getManager();
       $entity = $em->getRepository('CrijaReminderBundle:Event')->findOneby(array('id' => $eventId, 'user' => $user));


       //$date_modify    = str_replace("+", "-", $entity->getPeriodicity());
       //$completedAt    = $completedAtDate->modify($date_modify);
       //$entity->setCompletedAt($completedAt);


        $entity->setCompletedAt($completedAtDate);
       
       $em->persist($entity);
       $em->flush();
       
        return $this->redirect($this->generateUrl('event'));
    }
 /**
     * Delete a Event entity.
     *
     * @Route("/borrar/{id}", name="event_borrar")
     */
    public function borrarAction(Request $request, $id)
    {
            $user   = $this->get('security.context')->getToken()->getUser();
            $em     = $this->getDoctrine()->getManager();
            if (!$user) {
               throw $this->createNotFoundException('Imposible localizar al usuario');
             }

src/Crija/Bundle/ReminderBundle/Resources/views/Event/edit.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Event edit</h1>

    {{ form(edit_form) }}

        <ul class="record_actions">
    <li>
        <a href="{{ path('event') }}">
            Back to the list
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Crija/Bundle/ReminderBundle/Resources/views/Event/index.html.twig
{% extends "JalisFrontendBundle::layout_panel.html.twig" %}

{% block body -%}
<div class="front">
    <h4 style="display: inline-block;"><i class="fa fa-plus-circle fa-1x"></i>NOTIFICACIONES</h4>
    <a class="btn btn-danger btn-lg hidden-phone hidden-tablet hidden-xs hidden-sm" style="margin-right:10px;top:80px;float:right;" href="{{ path('event_new') }}">
        <i class="fa fa-calendar fa-3"></i><span style="font-size:17px"> Nuevo Evento</span>
    </a>
</div>

<div class="col-lg-12 front bright-top bright-bottom" style="min-height:200px">
     <div class="col-lg-10 col-lg-offset-1">
         <a href="{{ path('event_new') }}" class="btn btn-danger btn-lg hidden-desktop hidden-lg hidden-md" style="display:block;top:80px;" >
             <i class="fa fa-calendar fa-3"></i><span style="font-size:20px"> Nuevo Evento</span>
         </a>
        {% render controller("CrijaReminderBundle:Event:widget" ) %}
    </div>
</div>

{% endblock %}

src/Crija/Bundle/ReminderBundle/Resources/views/Event/new.html.twig
{% extends "JalisFrontendBundle::layout_panel.html.twig" %}

{% block body -%}
<div class="front">  
<h4><i class="fa fa-plus-circle fa-1x"></i>NUEVA NOTIFICACION</h4>
</div>


<form name="crija_bundle_reminderbundle_event" method="post" action="/app_dev.php/event/">
<div class="col-lg-12 back">

	<div class="col-md-offset-1 col-lg-5 water_imput">
		<div class="input-group input-group-lg">
		  <span class="input-group-addon">Tipo<span style="font-size:10"> ppm</span></span>
		   {{ form_widget(form.type, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
        <div class="col-md-offset-1 col-lg-5 water_imput">
		<div class="input-group input-group-lg">
		  <span class="input-group-addon">Fecha<span style="font-size:10"> ppm</span></span>
		   {{ form_widget(form.startedAt, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
        <div class="col-md-offset-1 col-lg-5 water_imput">
		<div class="input-group input-group-lg">
		  <span class="input-group-addon">Periodicidad<span style="font-size:10"> ppm</span></span>
		   {{ form_widget(form.periodicity, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
          <div class="col-md-offset-1 col-lg-5 water_imput">
		<div class="input-group input-group-lg">
		  <span class="input-group-addon">Mensaje<span style="font-size:10"> ppm</span></span>
		   {{ form_widget(form.message, {'attr': {'class': 'form-control'}}) }}
		</div>
	</div>
</div>      

<div style="display: none;">{{ form_rest(form) }}</div>
 <div class="col-lg-12 crystal-header-bottom">
	          <button type="submit" class="btn-mini"><i class="fa fa-download fa-3"></i><br><span style="font-size:15px">Guardar</span></button>
	    </div>
</form>


{% endblock %}

src/Crija/Bundle/ReminderBundle/Resources/views/Event/number.html.twig
<div class="badge-notification">{{number}}</div>

src/Crija/Bundle/ReminderBundle/Resources/views/Event/show.html.twig
{% extends '::base.html.twig' %}

{% block body -%}
    <h1>Event</h1>

    <table class="record_properties">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ entity.id }}</td>
            </tr>
            <tr>
                <th>Type</th>
                <td>{{ entity.type }}</td>
            </tr>
            <tr>
                <th>Active</th>
                <td>{{ entity.active }}</td>
            </tr>
            <tr>
                <th>Startedat</th>
                <td>{{ entity.startedAt|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Createdat</th>
                <td>{{ entity.createdAt|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Updatedat</th>
                <td>{{ entity.updatedAt|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Completedat</th>
                <td>{{ entity.completedAt|date('Y-m-d H:i:s') }}</td>
            </tr>
            <tr>
                <th>Message</th>
                <td>{{ entity.message }}</td>
            </tr>
            <tr>
                <th>Periodicity</th>
                <td>{{ entity.periodicity }}</td>
            </tr>
        </tbody>
    </table>

        <ul class="record_actions">
    <li>
        <a href="{{ path('event') }}">
            Back to the list
        </a>
    </li>
    <li>
        <a href="{{ path('event_edit', { 'id': entity.id }) }}">
            Edit
        </a>
    </li>
    <li>{{ form(delete_form) }}</li>
</ul>
{% endblock %}

src/Crija/Bundle/ReminderBundle/Resources/views/Event/widget.html.twig
{% if(entities|length >0 ) %}
{% for entity in entities %}
<form name="complete-reminder" method="post" action="{{path('complete-reminder')}}" class="form-inline">
    <div class="alert alert-{{ entity.priority }}" role="alert">
        {% if entity.type == 0 %}
            {% set info =  'Alerta periodica cada ' ~ entity.periodo ~ ' dias'  %}
        {% else %}
            {% set info = 'Alerta puntual' %}
        {% endif %}
             <div class="col-lg-6"><i class="fa fa-bell"></i> {{ info }}<br> Quedan {{entity.countDown}} dias para "{{ entity.message }}"</div>
              <input type="hidden" value="{{entity.id}}" id="event" name="event">
              <input type="datetime" value="{{entity.completedAt|date('Y-m-d')}}" class="form-control datepicker event{{entity.id}}" name="completedAt" id="event{{ entity.id }}"><input type="submit" value="guardar nueva fecha" class="btn btn-info">
             <a href="{{ path('event_borrar', {'id': entity.id}) }}" class="btn btn-danger">
               <i class="fa fa-bell-slash-o"></i>
            </a>   
              <script>
              $(function() {
              $( ".event{{entity.id}}" ).datepicker({ dateFormat: 'yy-mm-dd' });
              });
              </script>
    </div>
 </form>   

{% endfor %}
{% else %}
<div class="alert alert-warning" role="alert">No hay notificaciones creadas. Da de alta tu primera notificacion desde aqui: <a href="{{ path('event_new') }}" class="btn btn-danger" style="top:30px;">
               <i class="fa fa-calendar"></i> nuevo
            </a></div>
{% endif %}